### ISSUE TITLE
device.InstallationProxyBrowse() 获取结果不全

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gidevice#27]
device.InstallationProxyBrowse(giDevice.WithApplicationType(giDevice.ApplicationTypeUser)) 无论最后有没有加上筛选，获取出来的结果比较少，手机上的抖音等等获取不到

**Comment by electricbubble** [comment]
fixed [v0.4.3](https://github.com/electricbubble/gidevice/releases/tag/v0.4.3)
