### ISSUE TITLE
receive packet: plist: type mismatch: tried to decode plist type `array' into value of type

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gidevice#29]
在开发新的service模块，但是用LockdownBasicResponse解析会有问题，应该是要用自定义的response plist结构解析，但是没法知道原本的xml结构是怎样，有办法吗？

**Comment by ZhouYixun** [comment]
![image](https://user-images.githubusercontent.com/56339314/169880507-248fc474-1a13-4d32-8bbd-5af24e148f5e.png)

**Comment by electricbubble** [comment]
可开启 `debug` 模式，会打印所有的请求和响应

```golang
giDevice.SetDebug(true, true)
```

**Comment by ZhouYixun** [comment]
> 可开启 `debug` 模式，会打印所有的请求和响应
> 
> ```go
> giDevice.SetDebug(true, true)
> ```

我试试

**Comment by ZhouYixun** [comment]
> ```go
> giDevice.SetDebug(true, true)
> ```

同样是乱码

**Comment by ZhouYixun** [comment]
我再研究下

**Comment by electricbubble** [comment]
https://github.com/electricbubble/gidevice/blob/41fd114a5e7cbaa5ce2f1c3dc66281cab7b75c6b/pkg/libimobiledevice/lib.go#L9-L15

要么使用了错误的 `Packet`

或者需要实现新的 `Packet`

**Comment by ZhouYixun** [comment]
已解决，返回原来不是plist结构

**Comment by ZhouYixun** [comment]
> https://github.com/electricbubble/gidevice/blob/41fd114a5e7cbaa5ce2f1c3dc66281cab7b75c6b/pkg/libimobiledevice/lib.go#L9-L15
> 
> 要么使用了错误的 `Packet`
> 
> 或者需要实现新的 `Packet`

嗯嗯是的
