### ISSUE TITLE
iOS15.5 xctest err: dtx: get result: timeout after 30.0002822s

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gidevice#31]
我这只有一台测试机，还不知道是不是ios15.5的问题
挂载后直接device.xctest会出现WebDriverAgent server start failed: dtx: get result: timeout after 30.0002822s
有头绪吗

**Comment by ZhouYixun** [comment]
手机曾经可以启动，有显示wda的url，然后第二次开始就这样了。
超时报错之前，手机仍然有UIAutomating的蒙版

**Comment by electricbubble** [comment]
已知问题，在反复起停 `xctest`时，也会较低概率出现。

猜测是停止后，存在某种状态未能立刻结束，在这种状态下立刻启动 `xctest`，就会导致其中一请求无法得到预期的响应。

稍等几秒后，再启动应该就没问题了。

暂无想法如何完全避免这个问题。

**Comment by ZhouYixun** [comment]
> 已知问题，在反复起停 `xctest`时，也会较低概率出现。
> 
> 猜测是停止后，存在某种未能立刻结束的状态，在这种状态下立刻启动 `xctest`，就会导致其中一请求无法得到预期的响应。
> 
> 稍等几秒后，再启动应该就没问题了。
> 
> 暂无想法如何完全避免这个问题。

稍等再起也还存在，手机、pc重启、wda重装也还会，我是闲置手机一天才正常。。正常后第二次执行又开始了

**Comment by electricbubble** [comment]
插拔连接后依旧如此？

**Comment by electricbubble** [comment]
我手上的设备无法复现

**Comment by ZhouYixun** [comment]
> 我手上的设备无法复现

https://github.com/SonicCloudOrg/sonic-ios-bridge/blob/main/cmd/wda.go 我代码重复试也没问题，以前也没遇过这个问题，我过几天找个不是15.5的手机试试看，看下是不是15.5引起的

**Comment by ZhouYixun** [comment]
15.0没出现，看来估计是15.5引起的

**Comment by ZhouYixun** [comment]
不对，我用tidevice的话，15.5还是很稳定，反复开启wda都没问题，这个[dtx: get result: timeout after 30.0002822s]是需要重新挂载吗？我现在执行xctest之前检查device.images()是否存在还有签名len是否为0

**Comment by electricbubble** [comment]
注释掉这个操作试试 👇

https://github.com/electricbubble/gidevice/blob/a31cdff57d0fc234acf4a57d6f707a7b67a23f8d/device.go#L745-L747

**Comment by ZhouYixun** [comment]
> 

ok我尝试下

**Comment by ZhouYixun** [comment]
> 注释掉这个操作试试 👇
> 
> https://github.com/electricbubble/gidevice/blob/a31cdff57d0fc234acf4a57d6f707a7b67a23f8d/device.go#L745-L747

注释掉是可以的，反复启动都可以

**Comment by electricbubble** [comment]
fixed [v0.5.1](https://github.com/electricbubble/gidevice/releases/tag/v0.5.1)

**Comment by ZhouYixun** [comment]
> fixed [v0.5.1](https://github.com/electricbubble/gidevice/releases/tag/v0.5.1)

这个能解释下为什么注释observing吗？
是不是因为跟这里重复唤起processcontrol？
 
> https://github.com/electricbubble/gidevice/blob/a31cdff57d0fc234acf4a57d6f707a7b67a23f8d/device.go#L678-L680

**Comment by electricbubble** [comment]
我暂时无法给出根本原因。

---

你说使用 [tidevice](https://github.com/alibaba/taobao-iphone-device) 不会出现这个问题，

而 [tidevice](https://github.com/alibaba/taobao-iphone-device) 并没有进行 `d.instruments.startObserving` 操作，

我以前也尝试过不进行这个操作，确实没什么影响，就这么留着也仅是因为并不会产生问题。

既然现在在 `iOS 15.5` 上可能导致不能稳定工作，同时 [tidevice](https://github.com/alibaba/taobao-iphone-device) 也没这个操作，

不如先完全取消这个操作，如果确实影响了其他版本的稳定性，再单独针对 `iOS 15.5` 做处理

**Comment by ZhouYixun** [comment]
> 我暂时无法给出根本原因。
> 
> 你说使用 [tidevice](https://github.com/alibaba/taobao-iphone-device) 不会出现这个问题，
> 
> 而 [tidevice](https://github.com/alibaba/taobao-iphone-device) 并没有进行 `d.instruments.startObserving` 操作，
> 
> 我以前也尝试过不进行这个操作，确实没什么影响，就这么留着也仅是因为并不会产生问题。
> 
> 既然现在在 `iOS 15.5` 上可能导致不能稳定工作，同时 [tidevice](https://github.com/alibaba/taobao-iphone-device) 也没这个操作，
> 
> 不如先完全取消这个操作，如果确实影响了其他版本的稳定性，再单独针对 `iOS 15.5` 做处理

明白了
