### ISSUE TITLE
[Q] xctest貌似会偶断

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gidevice#33]
xctest启动后几分钟不动会断开，访问/status也是死掉了，然后过阵子访问又可以，这情况发生概率有点高。断开期间已确认没有任何wda指令发送过去阻塞。tidevice没有这个问题，不知道是tidevice做的xctest监听异常就杀掉重启的功劳还是底层实现不一样呢？

**Comment by electricbubble** [comment]
概率有点高？

`gidevice` 是 [v0.5.1](https://github.com/electricbubble/gidevice/releases/tag/v0.5.1) 之前还是之后的版本？

`iOS` 是什么版本？

**Comment by ZhouYixun** [comment]
> 访问 `/status` 死掉是什么现象？请求超时？请求报错？ `xctest` 被中断需要重启？
> 
> 过阵子访问又可以？`xctest` 执行未被中断？只是等待一段时间后，`wda` 请求就恢复正常？
> 
> 在这现象出现期间，`xctest` 会有 `out` 消息吗？
> 
> `gidevice` 是 [v0.5.1](https://github.com/electricbubble/gidevice/releases/tag/v0.5.1) 之前还是之后的版本？
> 
> `iOS` 是什么版本？

访问/status是超时。然后过阵子访问又正常了，返回wda相关的信息。
这期间的out没有东西。
---
最近几个版本的，具体哪个版本真的不清楚。。
ios是15.1和15.5

**Comment by electricbubble** [comment]
最好验证下和 [v0.5.1](https://github.com/electricbubble/gidevice/releases/tag/v0.5.1) 有没有关系

**Comment by ZhouYixun** [comment]
0.5.0-0.5.2都一样
status:
![image](https://user-images.githubusercontent.com/56339314/172905196-2bd57c68-d159-48f9-b95f-c65689ba22e1.png)
xctest log:
![image](https://user-images.githubusercontent.com/56339314/172905295-e2eb3141-201a-435e-b419-840d76db2621.png)

我怀疑是我转发的时候出错。
但是我有尝试用gidevice-cli的forward一样不行

**Comment by electricbubble** [comment]
提供复现环境与步骤

**Comment by ZhouYixun** [comment]
> 提供复现环境与步骤

直接在gidevice的测试类运行了xctest，另外一边用了转发端口，然后浏览器每隔十秒访问一次status

**Comment by electricbubble** [comment]
我直接使用了 [gidevice-cli v0.8.0](https://github.com/electricbubble/gidevice-cli/releases/tag/v0.8.0)

20分钟执行无异常

```shell
gidevice forward -l=18100 -r=8100
```
```shell
COUNT=0 && while true ; do COUNT=`expr ${COUNT} + 1` && echo "[${COUNT}] 👇 $(date +%H:%M:%S) 👇" && curl -w "time_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_pretransfer: %{time_pretransfer}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n\n" -o /dev/null -s -L "http://localhost:18100/status" && sleep 10; done;
```

![image](https://user-images.githubusercontent.com/42672996/172989955-3ac58706-add9-4268-8f07-a9599c8473c9.png)

![image](https://user-images.githubusercontent.com/42672996/172990693-36a259c3-7d6d-4fb0-9a39-aaaf85eacf92.png)

**Comment by ZhouYixun** [comment]
> 

跟你一样，执行了xctest和forward也是不行，你是用什么wda？

**Comment by electricbubble** [comment]
[appium/WebDriverAgent](https://github.com/appium/WebDriverAgent)

**Comment by electricbubble** [comment]
数据线？

**Comment by ZhouYixun** [comment]
> 数据线？

原装的，应该不存在这个问题才对

**Comment by ZhouYixun** [comment]
> 数据线？

我写法是一个xctest启动，两个协程负责forward的，也没有问题啊。。你的ios是国行？

**Comment by ZhouYixun** [comment]
能看下你appium的iosdriver启动参数吗？感觉也有可能是这里造成

**Comment by ZhouYixun** [comment]
确认是wda偶现的问题，多次操作tap或者swipe会这样，我找到原因再reopen吧
