### ISSUE TITLE
com.apple.instruments.server.services.coreprofilesessiontap，返回的数据异常

### ISSUE THREAD

**Issue by luoshengheng** [electricbubble/gidevice#41]
**我这边正在基于gidevice开发Go版的性能监控工具，CPU、GPU、流量等功能已正常实现，当尝试实现统计帧率、jank次数、和卡顿率功能时，参考了py-ios-device中获取并解析[com.apple.instruments.server.services.coreprofilesessiontap](https://github.com/YueChen-C/py-ios-device/blob/main/demo/instrument_demo/coreprofilesessiontap.py)帧渲染数据的逻辑，发现gidevice返回的数据不正常，预期返回的数据长度应该是和py-ios-device一样(64的整数倍)，但实际测试返回的数据长度是随机没有规律的，如下图所示：**

1. py-ios-device返回的数据header： 
![企业微信截图_16682485471343](https://user-images.githubusercontent.com/31942473/201469996-772f2bd1-c35c-4847-adad-a6ffa79c6381.png)

2. gidevice返回的数据header：
![企业微信截图_16682488998392](https://user-images.githubusercontent.com/31942473/201470027-06301186-9b78-46ce-a431-ec99e6c1d63f.png)

**造成这种现象我觉得最大的可能是调用com.apple.instruments.server.services.coreprofilesessiontap时，传过去的参数没有被正确接受和解析，导致InstrumentsServer返回的不是预期的数据，希望大佬帮忙排查一下，参数结构如下图所示：**

1. py-ios-device传的参数：
![image](https://user-images.githubusercontent.com/31942473/201470391-5ef872d5-4227-42fa-a81a-8f7cac7b016f.png)

2. gidevice传的参数：
![image](https://user-images.githubusercontent.com/31942473/201471284-e6726c1d-6cb4-4c74-a650-c6c07621f4b7.png)

4. 尝试过在gidevice发送请求时，直接将aux替换成py-ios-device中的aux，返回的数据依旧异常：
![image](https://user-images.githubusercontent.com/31942473/201471186-370a074b-4267-44ea-962c-adeb92552880.png)

**Comment by electricbubble** [comment]
非常抱歉，最近工作事情过多，

我短时间无法及时处理目前存在的两个版本 [dev-performance-monitoring](https://github.com/electricbubble/gidevice/tree/dev-performance-monitoring) & [PR#40](https://github.com/electricbubble/gidevice/pull/40)

---

你是独立这两个版本重新开发了一版？

---

关于 `图2` 中问题，

这种基础类型 `gidevice` 是支持的，但我确实无法 `100%` 保证其 [Marshal](https://github.com/electricbubble/gidevice/blob/41fd114a5e7cbaa5ce2f1c3dc66281cab7b75c6b/pkg/nskeyedarchiver/nskeyedarchiver.go#L8) 结果是完全符合预期的，

或许你可以尝试下使用 `py-ios-device` 对这个 `args` 进行 `Marshal`，并与 `gidevice` 的 `Marshal` 结果进行一次对比？

**Comment by luoshengheng** [comment]
> 非常抱歉，最近工作事情过多，
> 
> 我短时间无法及时处理目前存在的两个版本 [dev-performance-monitoring](https://github.com/electricbubble/gidevice/tree/dev-performance-monitoring) & [PR#40](https://github.com/electricbubble/gidevice/pull/40)
> 
> 你是独立这两个版本重新开发了一版？
> 
> 关于 `图2` 中问题，
> 
> 这种基础类型 `gidevice` 是支持的，但我确实无法 `100%` 保证其 [Marshal](https://github.com/electricbubble/gidevice/blob/41fd114a5e7cbaa5ce2f1c3dc66281cab7b75c6b/pkg/nskeyedarchiver/nskeyedarchiver.go#L8) 结果是完全符合预期的，
> 
> 或许你可以尝试下使用 `py-ios-device` 对这个 `args` 进行 `Marshal`，并与 `gidevice` 的 `Marshal` 结果进行一次对比？

好的，那烦请大佬有空再帮忙排查一下吧，因为我已经搞了几天，没有其它头绪了。

1. 是的，我现在是在main分支上重新搞的一版
2. 像我描述的最后一张图一样，我直接在发送请求前，将`auxiliary`替换成`py-ios-device` `Marshal`后的`auxiliary`，返回的结果仍然不符合预期。

**Comment by luoshengheng** [comment]
是因为kdf2参数的类型是NSSet，gidevice目前缺少对NSSet类型参数编解码的逻辑，找了py-ios-device的作者帮忙支持了一下，目前问题已解决
